### ISSUE TITLE
lockscreen wallpaper issue

### ISSUE THREAD

**Issue by mohamadjavith1** [legendsayantan/ThemePatcher#2]
whenever i use patcher, i cannot set locksceen wallpaper by selecting apply to home and lockscreen. i want to reset settings and clear data of system launcher to set lockscreen wallpaper

**Comment by legendsayantan** [comment]
Can you use lockscreen wallpaper as home and lockscreen while you opt in for its trial?

**Comment by legendsayantan** [comment]
Closed for lack of activity.
